{% set name = "foundry-platform-sdk" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7dbbdfef668cd44d7aa1f1f6d8af8b100d1dd229cd8052ceafad9f904f7ce10e

build:
  entry_points:
    - foundry_v1 = foundry_sdk.v1.cli:cli
    - foundry_v2 = foundry_sdk.v2.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python 3.9
    - setuptools >=35.0.2
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.9
    - httpx >=0.25.0,<1.0.0
    - pydantic >=2.6.0,<3.0.0
    - typing-extensions >=4.7.1
    - annotated-types >=0.7.0

test:
  imports:
    - foundry_sdk
  commands:
    - pip check
    - foundry_v2 --help
  requires:
    - python 3.9
    - pip
    - click

about:
  home: https://github.com/palantir/foundry-platform-python
  summary: The official Python library for the Foundry API
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jsmith
    - tdeitch
    - jameszhang244
    - afloren-palantir
